### ISSUE TITLE
Scrolling facebook

### ISSUE THREAD

**Issue by MartinLichtblau** [Pauan/AutoScroll#12]
Using the hardware mouse to autoscroll you can click on the screen and the autoscroll won't get interrupted, in my scenario clicking like in facebook. 
With your extension that doesn't work, since the autoscrolling stops when clicking on like. 
Why to implement? To be consistent with the real mouse behavior. And for me it's a great feature to scroll through facebook absorbing all information, without having to stop at every post I like - very convenient and productive.

**Comment by Pauan** [comment]
Hi @MartinLichtblau,

Sorry for taking so long to get back to you on this. I'm not sure what you mean by "hardware mouse autoscroll".

I just tried autoscrolling in Firefox (using Firefox's built-in autoscroll), and the autoscroll stops when clicking. Does it continue autoscrolling for you in Firefox even when you click?

**Comment by MartinLichtblau** [comment]
Its was when touch clicking. But I use a different solution right now.

**Comment by Pauan** [comment]
I'm sorry that AutoScroll didn't do what you wanted, but I'm glad you were able to find another solution!
