### ISSUE TITLE
Scrolling while holding MMB down stopped working

### ISSUE THREAD

**Issue by DanMan** [Pauan/AutoScroll#16]
I'm using this with Vivaldi and since the update to v1.13.1008.34 (based on Chrome/62.0.3202.97) this stopped working. Clicking, then moving still works, but not holding the MMB down and moving.

Problem occurs on both Win7 and Ubuntu 16.04.3.

**Comment by Fry-kun** [comment]
I've heard somewhere that Chrome on Windows has this feature built-in, are you sure you don't just want to use that?

**Comment by DanMan** [comment]
I'm mostly on Ubuntu these days, and they don't seem to have put it in that version.

**Comment by Pauan** [comment]
I've had weird behavior with Chrome extensions on Vivaldi, I think they have a lot of bugs and missing features. I'll take a look and see if this is a bug in Vivaldi.

**Comment by DanMan** [comment]
Works in Vivaldi 1.15.1147.52 with Autoscroll 4.8
