### ISSUE TITLE
Scrollbar and mouse scrollwheel disabled after using autoscroll in tab

### ISSUE THREAD

**Issue by hcbd** [Pauan/AutoScroll#2]
Scrollbar and mouse scrollwheel are disabled after using autoscroll in tab untill page is reloaded.

Reproduce:
- find page on which you can scroll.
- use autoscroll (in my case middle button) to scroll down/up on the page
- middleclick to end autoscrolling
- trying to scroll using the scrollbar or mousewheel is impossible untill you reload the page

Chromium version: Version 45.0.2454.85 Built on Ubuntu 14.04, running on Linux Mint 17.2 (64-bit)
AutoScroll version: 4.1

**Comment by Pauan** [comment]
Thanks for the report. I'll fix this right away.

**Comment by Pauan** [comment]
This has been fixed in version 4.2
