### ISSUE TITLE
Autoscroll mouse wheel scrolling broken with Chromium 69.0.3497.81

### ISSUE THREAD

**Issue by KeithMyers** [Pauan/AutoScroll#20]
Just found out that mouse wheel scrolling is non functional after an auto update from Chromium 68.03440.106 to Chromium 69.0.3497.81.

Third button click scrolling is the only thing that works now.

**Comment by ivan** [comment]
Works for me in Chrome 69.0.3497.92 on Linux.

**Comment by KeithMyers** [comment]
Restarted Chrome several times.  No change.  Came back to it an hour later and it now works.  Go figure.  Don't know what happened after I updated.
