### ISSUE TITLE
Zoom in and zoom out using the mouse wheel

### ISSUE THREAD

**Issue by nitrocode** [Pauan/AutoScroll#23]
Thanks for a great extension!

It would be nice if I could also zoom in and zoom out using the mouse wheel.

**Comment by Pauan** [comment]
Thanks for the suggestion, but that doesn't really have anything to do with autoscrolling, right?

Also, Chrome has a built-in zoom feature: if you hold down Ctrl and use the mouse wheel it will zoom in and out.

**Comment by nitrocode** [comment]
@Pauan that's true. I guess it's more of an extension with of the middle mouse wheel. I meant more for zoom in and zoom out for google maps.

**Comment by Pauan** [comment]
What do you mean? I just now tested it, and mouse wheel already zooms in and out on Google Maps.

Are you using a Google Maps App or Extension or something like that?

**Comment by nitrocode** [comment]
On linux it doesn't seem to work. I haven't checked on mac though.
