### ISSUE TITLE
Element.createShadowRoot removed in Chrome 73

### ISSUE THREAD

**Issue by nazrhyn** [Pauan/AutoScroll#24]
I noticed this deprecation warning in the console:

```
[Deprecation] Element.createShadowRoot is deprecated and will be removed in M73, around March 2019.
Please use Element.attachShadow instead.
See https://www.chromestatus.com/features/4507242028072960 for more details.
```
Your source has:
```js
// TODO replace with `attachShadow` once it's supported in Chrome
// https://developer.mozilla.org/en-US/docs/Web/API/Element/createShadowRoot
var shadow = (outer.createShadowRoot
               ? outer.createShadowRoot()
               // TODO hack for Chrome 29 to 34, remove this later
               : outer.webkitCreateShadowRoot())
```

It looks like the time is coming for this TODO to get resolved. Hooray.

Maybe something like...

```js
var createShadow = outer.attachShadow || outer.createShadowRoot || outer.webkitCreateShadowRoot;
var shadow = createShadow.call(outer);
```

Thanks for making this extension. :heart: The middle-click-to-scroll thing is something I'm so used to from Windows, I kind of freaked out when it didn't work in Linux.

**Comment by Pauan** [comment]
Thanks for the report! It was [already fixed](https://github.com/Pauan/AutoScroll/pull/22) a while ago, I just need to release a new version to the Chrome Store.

**Comment by nazrhyn** [comment]
Oh, good. I did a search for "shadow" and didn't see one. I look forward to the new release, then!

**Comment by Pauan** [comment]
Just a heads up that version 4.9 has been released on the Chrome Web Store. It fixes the deprecation warning.
