### ISSUE TITLE
[Regression] Middle click to paste does not work in many inputs/textareas on Linux

### ISSUE THREAD

**Issue by DanielNoga** [Pauan/AutoScroll#26]
When plugin is enabled with middle click to scroll, it is not possible to use middle click to paste inside many inputs and text areas. For example in Youtube search bar or here inside reporting bug textarea. Some inputs work fine, for example textarea inside Google translate. 

It worked in past, not sure when it stoped working. Because it is not possible to downgrade Chrome or plugin, I am not sure if it is in new version of Chrome or a new version of this plugin. My setup is Linux with KDE, Chrome 70.0.3538.77, Autoscroll version 4.9

**Comment by Pauan** [comment]
Thanks for the report! This should be fixed with version 4.10
