### ISSUE TITLE
This might make middle click able to paste in inputs.

### ISSUE THREAD

**Issue by noah2828** [Pauan/AutoScroll#3]
I have not had time to take a look at your code but I just threw this together it should allow use of middle click paste when in inputs.

    $(document).ready(function () {
        $("input").on("click", function () {
            if ($(this).is(':focus')) {
                //disable AutoScroll
            }
        });
    
        $("input").blur(function () {
            //enable AutoScroll 
        });
    });

**Comment by Pauan** [comment]
AutoScroll already allows for pasting using middle click.

Did you try disabling the "Scroll when clicking on a link or textarea" option?

**Comment by noah2828** [comment]
Yes that is disabled by default YouTube and Quora I have also tried disabling the inner scroll option with the same result.

**Comment by Pauan** [comment]
Okay, I just tried the YouTube comment section and you're right, it doesn't work.

But your code won't fix it, because the problem is with `contenteditable`

I already have a TODO for ` contenteditable`, so I guess it's time to properly implement it.

Thanks for the report.

**Comment by noah2828** [comment]
Ok thanks.

**Comment by noah2828** [comment]
My bad about it being `contenteditable` I should have made sure what the problem was before rapidly throwing together code.
