### ISSUE TITLE
Not work on some sites

### ISSUE THREAD

**Issue by poseidonn** [Pauan/AutoScroll#6]
After the last update does not work on some sites.

example: 
http://www.indiewire.com/
http://www.teknoseyir.com/

**Comment by hcbd** [comment]
I can confirm this bug.
The site http://www.nu.nl doesn't scoll when the cookiewarning is present.
The scrolling works fine when the cookiewarning has been closed/agreed with.

autoscroll 4.6
chromium: Version 48.0.2564.82 Built on Ubuntu 14.04, running on LinuxMint 17.3 (64-bit)

**Comment by treyp** [comment]
I believe this will be fixed once the latest code is released. At least, it works fine for me in testing. Any idea when that will happen, @Pauan?

**Comment by Pauan** [comment]
I just released version 4.7, which fixes this bug.

Thanks for your help in finding and fixing this bug.
